//
//  HomePageInteractor.swift
//  Project_Sandro_Giorgishvili
//
//  Created by TBC on 02.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePageBusinessLogic
{
  func doSomething(request: HomePage.Something.Request)
}

protocol HomePageDataStore
{
  //var name: String { get set }
}

class HomePageInteractor: HomePageBusinessLogic, HomePageDataStore
{
  var presenter: HomePagePresentationLogic?
  var worker: HomePageWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: HomePage.Something.Request)
  {
    worker = HomePageWorker()
    worker?.doSomeWork()
    
    let response = HomePage.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
