//
//  HomePagePresenter.swift
//  Project_Sandro_Giorgishvili
//
//  Created by TBC on 02.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePagePresentationLogic
{
  func presentSomething(response: HomePage.Something.Response)
}

class HomePagePresenter: HomePagePresentationLogic
{
  weak var viewController: HomePageDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: HomePage.Something.Response)
  {
    let viewModel = HomePage.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
