//
//  LoginPresenter.swift
//  Project_Sandro_Giorgishvili
//
//  Created by TBC on 16.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
    func presentEmptyErrorLabels(response: Login.EmptyErrorLabels.Response)
    func presentEmptyEmailError(response: Login.DisplayErrorLabel.Response)
    func presetnEmptyPasswordError(response: Login.DisplayErrorLabel.Response)
    func presentSuccessfullLogin(response: Login.Success.Response)
    func presentLoginFailed(response: Login.Fail.Response)
}

final class LoginPresenter {
    // MARK: - Clean Components
    
    weak var viewController: LoginDisplayLogic?
}

// MARK: - LoginPresentationLogic

extension LoginPresenter: LoginPresentationLogic {
    func presentLoginFailed(response: Login.Fail.Response) {
        viewController?.displayLoginFailed(ViewModel: Login.Fail.ViewModel(title: nil, errorMessage: Constants.ErrorMessages.logInError))
    }
    
    func presentEmptyErrorLabels(response: Login.EmptyErrorLabels.Response) {
        viewController?.displayEmptyErrorLabels(ViewModel: Login.EmptyErrorLabels.ViewModel())
    }
    
    func presentSuccessfullLogin(response: Login.Success.Response) {
        viewController?.displaySuccessfullLogin(ViewModel: Login.Success.ViewModel())
    }
    
    func presentEmptyEmailError(response: Login.DisplayErrorLabel.Response) {
        viewController?.displayEmptyEmail(ViewModel: Login.DisplayErrorLabel.ViewModel(errorMessage: Constants.ErrorMessages.emptyField))
    }
    
    func presetnEmptyPasswordError(response: Login.DisplayErrorLabel.Response) {
        viewController?.displayEmptyPassword(ViewModel: Login.DisplayErrorLabel.ViewModel(errorMessage: Constants.ErrorMessages.emptyField))
    }
}
